drop table if exists USERS;

create table USERS(
ID INT AUTO_INCREMENT PRIMARY KEY,
F_NAME VARCHAR(100) NOT NULL,
L_NAME VARCHAR(100),
USER_ID VARCHAR(50));

INSERT INTO USERS(F_NAME,L_NAME,USER_ID) VALUES
('VIRAT','KOHLI','CHIKU'),
('ROHIT','SHARMA','MOTA'),
('JASPREET','BHUMRA','BOOM'),
('BHUVANESHWAR','KUMAR','BHUVI'),
('MAYANK','AGARWAL','MICKY');